// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKTzUnOprsdi5yy7HgzmxdsCfuC8oDE-E',
    appId: '1:142393083383:web:c020370104032b351a1af2',
    messagingSenderId: '142393083383',
    projectId: 'human-crisis-app',
    authDomain: 'human-crisis-app.firebaseapp.com',
    storageBucket: 'human-crisis-app.firebasestorage.app',
    measurementId: 'G-WLF6KL8J76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABimluQR1ceOU80pdQUrSfPQk0ucTaPeQ',
    appId: '1:142393083383:android:9c40550192b8cc901a1af2',
    messagingSenderId: '142393083383',
    projectId: 'human-crisis-app',
    storageBucket: 'human-crisis-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsQXYH1kJqYu3ORi80HGtxPApmSw_D-RU',
    appId: '1:142393083383:ios:aaa371779d9e7f001a1af2',
    messagingSenderId: '142393083383',
    projectId: 'human-crisis-app',
    storageBucket: 'human-crisis-app.firebasestorage.app',
    iosBundleId: 'com.example.crisisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsQXYH1kJqYu3ORi80HGtxPApmSw_D-RU',
    appId: '1:142393083383:ios:aaa371779d9e7f001a1af2',
    messagingSenderId: '142393083383',
    projectId: 'human-crisis-app',
    storageBucket: 'human-crisis-app.firebasestorage.app',
    iosBundleId: 'com.example.crisisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKTzUnOprsdi5yy7HgzmxdsCfuC8oDE-E',
    appId: '1:142393083383:web:9de63089b792b60f1a1af2',
    messagingSenderId: '142393083383',
    projectId: 'human-crisis-app',
    authDomain: 'human-crisis-app.firebaseapp.com',
    storageBucket: 'human-crisis-app.firebasestorage.app',
    measurementId: 'G-63812EMM9N',
  );
}
